In [33]:
import pandas as pd
import numpy as np

In [43]:
data = pd.read_csv("C:spam.csv")
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [45]:
data.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [46]:
data["Spam"] = data["Category"].apply(lambda x : 1 if x == "spam" else 0)
data.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [47]:
data.drop("Category",axis=1,inplace=True)
data.head()

Message  Spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [48]:
x = data.Message
y = data.Spam

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_new = v.fit_transform(x.values)
x_new.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [90]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_new,y,test_size=0.2,random_state=1)

In [91]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [92]:
model.fit(x_train,y_train)

MultinomialNB()

In [93]:
model.score(x_test,y_test)

0.9883408071748879

In [98]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, x_new, y, cv=5)
scores

array([0.97847534, 0.9793722 , 0.97845601, 0.98114901, 0.97935368])

In [99]:
# Pipeline

x = data.Message
y = data.Spam

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)

from sklearn.feature_extraction.text import CountVectorizer  
from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline
clf = Pipeline([
    ("vectorize", CountVectorizer()),
    ("nb", MultinomialNB())
])

clf.fit(x_train, y_train)

Pipeline(steps=[('vectorize', CountVectorizer()), ('nb', MultinomialNB())])

In [101]:
clf.score(x_test,y_test)

0.989237668161435

In [105]:
# Prediction

emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

clf.predict(emails)

array([0, 1], dtype=int64)